<?php

function notify($to,$data){

    $api_key="AAAAriAGwl8:APA91bGExbw5qr98W387pKDm62uJuMlp01xxGoNlyFj5nntrrJOZZTafTo_8PG7EH3-2JpSWLSl6zN9lJnLOoSzuz1lWQIr6fYrAvZEXIjA3XFhcmCtvyrrgefD4X3P4NTQEPF0NGXeG";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'notification'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$to="";
$data=array(
    'title'=>'Main malam-malam',
    'body'=>'Keep never tired learning!'
);

notify($to,$data);
echo "Notification Sent";

?>